name: Build Yukimi Artifact

on:
  workflow_call:
  workflow_dispatch:

env:
  APK_PATH: app/build/outputs/apk/nightly/app-nightly.apk

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Pull upstream ðŸŒ
        uses: actions/checkout@v4
        with:
          repository: YakaTeam/app
          ref: base
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK ðŸš€
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle ðŸš€
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Android SDK ðŸš€
        uses: android-actions/setup-android@v3

      - name: Build Yukimi APK (Attempt 1) ðŸ’»
        run: |
          chmod a+x gradlew
          ./gradlew assembleNightly \
          -DparsersVersionOverride=$(curl -s https://api.github.com/repos/YakaTeam/kotatsu-parsers/commits/master -H "Accept: application/vnd.github.sha" | cut -c -10)
        continue-on-error: true
        timeout-minutes: 30

      - name: Build Yukimi APK (Attempt 2) ðŸ’»
        run: >-
          if [ ! -f ${{ env.APK_PATH }} ]; then
            pkill -f java &&
            ./gradlew assembleNightly \
            -DparsersVersionOverride=$(curl -s https://api.github.com/repos/YakaTeam/kotatsu-parsers/commits/master -H "Accept: application/vnd.github.sha" | cut -c -10)
          else
            echo "âœ… Yukimi build already exists, skipping build attempt 2";
          fi
        continue-on-error: true
        timeout-minutes: 30

      - name: Build Yukimi APK (Attempt 3) ðŸ’»
        run: >-
          if [ ! -f ${{ env.APK_PATH }} ]; then
            pkill -f java &&
            ./gradlew assembleNightly \
            -DparsersVersionOverride=$(curl -s https://api.github.com/repos/YakaTeam/kotatsu-parsers/commits/master -H "Accept: application/vnd.github.sha" | cut -c -10)
          else
            echo "âœ… Yukimi build already exists, skipping build attempt 3";
          fi
        continue-on-error: true
        timeout-minutes: 30

      - name: Build Yukimi APK (Attempt 4) ðŸ’»
        run: >-
          if [ ! -f ${{ env.APK_PATH }} ]; then
            pkill -f java &&
            ./gradlew assembleNightly \
            -DparsersVersionOverride=$(curl -s https://api.github.com/repos/YakaTeam/kotatsu-parsers/commits/master -H "Accept: application/vnd.github.sha" | cut -c -10)
          else
            echo "âœ… Yukimi build already exists, skipping build attempt 4";
          fi
        continue-on-error: true
        timeout-minutes: 30

      - name: Build Yukimi APK (Attempt 5) ðŸ’»
        run: >-
          if [ ! -f ${{ env.APK_PATH }} ]; then
            pkill -f java &&
            ./gradlew assembleNightly \
            -DparsersVersionOverride=$(curl -s https://api.github.com/repos/YakaTeam/kotatsu-parsers/commits/master -H "Accept: application/vnd.github.sha" | cut -c -10)
          else
            echo "âœ… Yukimi build already exists, skipping build attempt 5";
          fi
        continue-on-error: false
        timeout-minutes: 30

      - name: Upload APK artifact ðŸ“¤
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: ${{ env.APK_PATH }}
          retention-days: 1

  release:
    needs: build
    uses: ./.github/workflows/release.yml
    secrets: inherit

  update:
    needs: build
    uses: ./.github/workflows/update.yml
    secrets: inherit
